exports.JavaScriptList = [
  "JavaScript/DOM.md",
  "JavaScript/Web-Storage",
  "JavaScript/airbnb-javascript-style-guide",
  "JavaScript/ajax",
  "JavaScript/array-shuffle",
  "JavaScript/bom",
  "JavaScript/box-javascript-refactoring",
  "JavaScript/browser-compability",
  "JavaScript/call-apply",
  "JavaScript/call-by-sharing",
  "JavaScript/closure",
  "JavaScript/date-type",
  "JavaScript/disable-body-scrolling",
  "JavaScript/es2015-classes",
  "JavaScript/es2015",
  "JavaScript/es6-generators",
  "JavaScript/event-bubbling",
  "JavaScript/event-delegation",
  "JavaScript/event-target-vs-currunttarget",
  "JavaScript/event",
  "JavaScript/graph-ql",
  "JavaScript/indexeddb",
  "JavaScript/javascript-assign-function-without-run",
  "JavaScript/javascript-codeschool",
  "JavaScript/javascript-design-pattern",
  "JavaScript/javascript-download-from-get-url",
  "JavaScript/javascript-run-function",
  "JavaScript/javascript-switch-with-regex",
  "JavaScript/javascript-template-handlebar",
  "JavaScript/javascript-tips",
  "JavaScript/javascript-unlock",
  "JavaScript/jpub-ajax-json",
  "JavaScript/jquery-plugin",
  "JavaScript/js-unit-test",
  "JavaScript/map",
  "JavaScript/meteor",
  "JavaScript/mobile-web",
  "JavaScript/okky-conference",
  "JavaScript/print-page",
  "JavaScript/promise",
  "JavaScript/prototype",
  "JavaScript/reference-type",
  "JavaScript/regular-expression",
  "JavaScript/short-circuit",
  "JavaScript/sparse-array-vs-dense-array",
  "JavaScript/udemy-react",
  "JavaScript/udemy-vue",
  "JavaScript/vuejs",
  "JavaScript/way-to-get-javascript-in-html",
  "JavaScript/bugs-in-ios8",
  "JavaScript/functional-programming",
  "JavaScript/functional-programming-with-lodash-fp",
  "JavaScript/typescript",
  "JavaScript/plz-answer",
];

exports.JavaList = []

exports.PythonList = [
  "Python/make-hobbycoding",
  "Python/make-jaystagram",
  "Python/python-set-environments",
  "Python/python-startkit",
  "Python/python",
];
exports.SQLList = []

exports.DailyAlgorithmList = [
  "Daily-Coding/191120-two-sum",
  "Daily-Coding/191119-remove-duplicates-from-sorted-array",
  "Daily-Coding/180110-recursion-davis-staircase",
  "Daily-Coding/180110-stacks",
  "Daily-Coding/array-helpers",
  "Daily-Coding/banner-sorting",
  "Daily-Coding/christmas-tree",
  "Daily-Coding/codewars-170922-factorial-tail",
  "Daily-Coding/counting-duplicates",
  "Daily-Coding/dc-171106-two-sum",
  "Daily-Coding/find-the-divisors",
  "Daily-Coding/get-random-number",
  "Daily-Coding/haming-numbers",
  "Daily-Coding/hello-what",
  "Daily-Coding/human-readable-time",
  "Daily-Coding/ip-validation",
  "Daily-Coding/javascript-round-floor-ceil",
  "Daily-Coding/moving-zeros-to-the-end",
  "Daily-Coding/numerology",
  "Daily-Coding/ordinal-numbers",
  "Daily-Coding/pick-peaks",
  "Daily-Coding/points-on-a-line",
  "Daily-Coding/power-of-two",
  "Daily-Coding/prefill-an-array",
  "Daily-Coding/return-substring-instance-count",
  "Daily-Coding/reverse-string-in-array",
  "Daily-Coding/square-matrix-multiplication",
  "Daily-Coding/sum-by-factors",
  "Daily-Coding/the-shell-game",
  "Daily-Coding/unique-in-order",
];

exports.GitList = [
  "Git/git-guide",
  "Git/git-ignore",
  "Git/git-reverse-commit",
  "Git/pro-git",
  "Git/rebase-with-sourcetree",
  "Git/trouble-shooting-on-console",
  "Git/rebase-vs-merge-commit",
  "Git/revert-certain-file",
];

exports.NetworkList = ["Network/ssh-tunneling"];

exports.DevOpsList = ["DevOps/docker.md", "DevOps/vupress-github-actions.md"];

exports.ETCList = [
  "ETC/amplitude",
  "ETC/beer",
  "ETC/readable-code",
  "ETC/2015-sanfrancisco-tour",
  "ETC/2017_NDC",
  "ETC/Gaekoboard_guide",
  "ETC/Markdown-Cheatsheet",
  "ETC/atom",
  "ETC/computer-graphics",
  "ETC/cool-stuff",
  "ETC/cross-browsing-with-pow",
  "ETC/daily-commit",
  "ETC/dash-vs-underscore",
  "ETC/eclipse-shortcut",
  "ETC/english-in-programming",
  "ETC/fundamentals-of-design-codeschool",
  "ETC/google-apps-201",
  "ETC/grid-layout",
  "ETC/heroku",
  "ETC/intellij-shortcut",
  "ETC/naver-deview-2015",
  "ETC/network",
  "ETC/node-easymock",
  "ETC/nodejs",
  "ETC/operation-system",
  "ETC/productivity",
  "ETC/pycharm-shortcut",
  "ETC/pycon-2015",
  "ETC/zendesk",
  "ETC/chrome-extension",
  "ETC/TIL",
  "ETC/vs-code",
  "ETC/swift-basic",
  "ETC/swift_doc",
  "ETC/career-ladders",
  "ETC/becoming-senior",
];

// exports.BundlerList = ["Bundler/grunt", "Bundler/webpack"];
